### ISSUE TITLE
Cloning struct fields directly

### ISSUE THREAD

**Issue by Cogitri** [clucompany/Enclose#1]
Hello,

first of: thanks for the useful macro, I use it all over my codebase :)

There's one thing I'm missing though, consider the following example:

```
self.gestures.drag.connect_drag_begin(
            enclose!((edit_view, self.gestures.drag_data => drag_data) move |_, start_x, start_y| {
                let new_data = DragData {
                    start_x,
                    start_y,
                };
                drag_data.replace(new_data);
            }),
        );
```

This will fail with something like:

```
error: no rules expected the token `.`
   --> src/editview/src/view_item.rs:154:38
       |
154 |             enclose!((edit_view, self.gestures.drag_data => drag_data) move |_, start_x, start_y| {
       |                                      ^ no rules expected this token in macro call
```

It'd be nice if I could clone the field directly instead of having to do `let drag_data = self.gestures.drag_data` and then cloning it with enclose

**Comment by denisandroid** [comment]
**Thank you that addressed.**
I did not notice this problem, but now I see that it is.
Tried to solve for =>' and rolled out updates on github.

```
1. Bug fix # 1

2. Added tests for bug # 1
3. Added macro for short circuit creation and start. (run_enclose!, run_enc!)
4. Documentation updated
5. Added example `cogitri_issue` for checking and excluding bug # 1
```
Url commit: https://github.com/clucompany/Enclose/commit/c4d41c1be96b7db1910a4355daf77cf6e170367e

**===============================**
Request, check whether this problem in your project is corrected, whether and also check new bugs appeared (tests can cover not everything). 

For check it is required to write to 'Cargo.toml'
```
[dependencies]
enclose = { git = "https://github.com/clucompany/Enclose" }
```

**Comment by Cogitri** [comment]
Seems to work with your new version. Thank you very much for your help and for this crate, it really makes my life a lot easier with my Rust project (https://github.com/Cogitri/Tau)! :)
