### ISSUE TITLE
Huge request, check the latest code base for errors in your projects.

### ISSUE THREAD

**Issue by denisandroid** [clucompany/Enclose#2]
Huge requesе, check the latest code base for errors in your projects.

Updates are related to move semantics in closures. Purpose: to exclude frequent move for closures ||.

Url: https://github.com/clucompany/Enclose/commit/b8755c5adcdcbd1ac8d65998a056466254aba60a

Connection to the project:
```
[dependencies]
enclose = { git = "https://github.com/clucompany/Enclose" }
```

**Comment by Cogitri** [comment]
Will test in Tau. Feel free to ping me next time :)

**Comment by Cogitri** [comment]
It doesn't seem to work if you have a closure where you don't want one of the inputs:
```
error: no rules expected the token `_`
   --> src/editview/src/edit_view.rs:145:62
    |
145 |         im_context.connect_commit(enclose!((edit_view) move |_, text| {
    |                                                              ^ no rules expected this token in macro call

```

This happens a lot in my codebase, see https://gitlab.gnome.org/World/Tau/blob/master/src/editview/src/edit_view.rs#L145 or https://gitlab.gnome.org/World/Tau/blob/master/src/editview/src/edit_view.rs#L129

**Comment by denisandroid** [comment]
Url: https://github.com/clucompany/Enclose/commit/ebde7e722d9a8970899693ae957fc204ec0df348

Recheck, especially with "move" and without "move"

**Comment by Cogitri** [comment]
Ah, I actually don't have any closure without `move` because I need `'static` for all of my closures :)

Will check with my existing stuff though, thank you!

**Comment by Cogitri** [comment]
Alright, the new version _almost_ works, the only error left is:

```
error: no rules expected the token `restart_search`
       --> src/editview/src/view_item.rs:515:53
       |
515 |             .connect_toggled(enclose!((ev) move |_| restart_search(ev.clone())));
       |                                                     ^^^^^^^^^^^^^^ no rules expected this token in macro call
```

I guess the macro doesn't account for single line calls which aren't delimited by curly braces.

**Comment by denisandroid** [comment]
```
connect_toggled(enclose!((ev) move |_| restart_search(ev.clone())))
```

Questions to the code, double clone?

**Comment by denisandroid** [comment]
Updated the code, url: https://github.com/clucompany/Enclose/commit/e0a30e7743641f6f1b6cf2f288eb7849abdf4929

**Comment by Cogitri** [comment]
> Questions to the code, double clone?

Oh derp, refactoring gone wrong there, thanks for noticing :P

**Comment by Cogitri** [comment]
The new version seems to work for me! :)

**Comment by denisandroid** [comment]
Ok, I'll review some things for now. If no bugs are found, I think I'll publish tonight.

**Comment by Cogitri** [comment]
Nice

**Comment by denisandroid** [comment]
I released an update on git, now left on crates. I don't think there should be any mistakes.

1.1.8 url: https://github.com/clucompany/Enclose/releases/tag/1.1.8

**Comment by Cogitri** [comment]
Works for me, thank you! :)
